/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SistemasSQL;

import com.mysql.cj.jdbc.ClientPreparedStatement;
import com.mysql.cj.jdbc.ConnectionImpl;
import com.mysql.cj.jdbc.StatementImpl;
import com.mysql.cj.jdbc.result.ResultSetImpl;
import conexãoSql.conexaoSQL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 554799103706
 */
public class usuario extends javax.swing.JFrame {

   conexaoSQL cc = new conexaoSQL();
    ConnectionImpl ccn = (ConnectionImpl) cc.conectar();
    public usuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    TrocarS janela = new TrocarS();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bntGuardar = new javax.swing.JButton();
        bntActualizar = new javax.swing.JButton();
        bntTrocar = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txtgmail = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablausuario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setText("NOME:");

        jLabel2.setText("CPF:");

        jLabel3.setText("SENHA:");

        jLabel4.setText("E-MAIL:");

        jLabel5.setText("TELEFONE:");

        bntGuardar.setText("Guardar");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });

        bntActualizar.setText("Actualizar");
        bntActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntActualizarActionPerformed(evt);
            }
        });

        bntTrocar.setText("Trocar senha");
        bntTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTrocarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bntGuardar)
                        .addGap(100, 100, 100)
                        .addComponent(bntActualizar))
                    .addComponent(txtnome)
                    .addComponent(txtcpf)
                    .addComponent(txttelefone)
                    .addComponent(txtgmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtsenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bntTrocar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcpf, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntTrocar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtgmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntGuardar)
                    .addComponent(bntActualizar))
                .addContainerGap())
        );

        tablausuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablausuario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablausuarioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablausuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablausuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        insertar();
        mostrardatosU();
        limparcajas();
    }//GEN-LAST:event_bntGuardarActionPerformed

    private void tablausuarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablausuarioAncestorAdded
        
    }//GEN-LAST:event_tablausuarioAncestorAdded

    private void tablausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablausuarioMouseClicked
        int filaSelecionada=tablausuario.rowAtPoint(evt.getPoint());
        txtnome.setText(tablausuario.getValueAt(filaSelecionada, 1).toString());
        txtcpf.setText(tablausuario.getValueAt(filaSelecionada, 2).toString());
        txtgmail.setText(tablausuario.getValueAt(filaSelecionada, 3).toString());
        txttelefone.setText(tablausuario.getValueAt(filaSelecionada, 5).toString());
        txtgmail.setText(tablausuario.getValueAt(filaSelecionada, 4).toString());
    }//GEN-LAST:event_tablausuarioMouseClicked

    private void bntActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntActualizarActionPerformed
         actualizardatos();
    }//GEN-LAST:event_bntActualizarActionPerformed

    private void bntTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTrocarActionPerformed
         janela = new TrocarS();
        janela.setVisible(true);
        janela.setLocationRelativeTo(null);
    }//GEN-LAST:event_bntTrocarActionPerformed
public void insertar(){
    
    try{
        String SQL="insert into usuario (Nome, cpf, senha, gmail, telefone) values (?,?,?,?,?)";
        
        ClientPreparedStatement pst = (ClientPreparedStatement) ccn.prepareStatement(SQL);
        
        pst.setString(1, txtnome.getText());
        pst.setString(2, txtcpf.getText());
        pst.setString(4, txtgmail.getText());
        pst.setString(5, txttelefone.getText());
        pst.setString(3, txtgmail.getText());
        
        pst.execute();
        
       JOptionPane.showMessageDialog(null,"registro exitosso \n");
        
    }catch(Exception e ){
        JOptionPane.showMessageDialog(null,"error de registro  \n " + e.getMessage());
    }
}
public void mostrardatosU(){
      String[] titulos={"id","nome","cpf","senha","gmail","telefone","ativo"};
      String [] registro=new String[10];
      DefaultTableModel modelo = new DefaultTableModel(null,titulos);
      String SQL="select * from usuario";
     try{
          StatementImpl st = (StatementImpl) cc.conectar().createStatement();
          ResultSetImpl rs =(ResultSetImpl) st.executeQuery(SQL);
         while (rs.next()){
             registro[0]=rs.getString("id");
             registro[1]=rs.getString("nome");
             registro[2]=rs.getString("cpf");
             
             registro[4]=rs.getString("gmail");
             registro[5]=rs.getString("telefone");
             registro[6]=rs.getString("ativo");
             modelo.addRow(registro);
         }
         tablausuario.setModel(modelo);
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Error al mostrar datos" +  e.getMessage());
         
     }


}
public void limparcajas(){
    txtnome.setText("");
    txtcpf.setText("");
    txtgmail.setText("");
    txttelefone.setText("");
    txtgmail.setText("");
    
    
}
public void actualizardatos(){
    
    try{
        String SQL=" update admin set Nome=?, cpf=?, senha=?, gmail=?, telefone=? where id=? ";
        int filaSelecionada = tablausuario.getSelectedRow();
        String dao = (String)tablausuario.getValueAt(filaSelecionada, 0);
        ClientPreparedStatement pst = (ClientPreparedStatement) ccn.prepareStatement(SQL);
        
        pst.setString(1, txtnome.getText());
        pst.setString(2, txtcpf.getText());
        pst.setString(4, txtgmail.getText());
        pst.setString(5, txttelefone.getText());
        pst.setString(3, txtgmail.getText());
        
        pst.setString(6, dao);
      
        pst.execute();
        
        JOptionPane.showMessageDialog(null,"registro atualizado \n");
        
    }catch(Exception e ){
        JOptionPane.showMessageDialog(null,"error de atualização registro  \n " + e.getMessage());
    }
      }
public void filtrardatosU(String valor){
      String[] titulos={"id","nome","cpf","senha","gmail","telefone","ativo"};
      String [] registro=new String[7];
      DefaultTableModel modelo = new DefaultTableModel(null,titulos);
      String SQL="select * from usuario where nome like '%"+valor+"%'";
     try{
          StatementImpl st = (StatementImpl) cc.conectar().createStatement();
          ResultSetImpl rs =(ResultSetImpl) st.executeQuery(SQL);
         while (rs.next()){
             registro[0]=rs.getString("id");
             registro[1]=rs.getString("nome");
             registro[2]=rs.getString("cpf");
             
             registro[4]=rs.getString("gmail");
             registro[5]=rs.getString("telefone");
             registro[6]=rs.getString("ativo");
             modelo.addRow(registro);
         }
         tablausuario.setModel(modelo);
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Error al mostrar datos" +  e.getMessage());
         
     }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntActualizar;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JButton bntTrocar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablausuario;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtgmail;
    private javax.swing.JTextField txtnome;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
